name: job_matching_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  adaptive_theme: ^3.6.0
  shared_preferences: ^2.0.0
  flutter_radar_chart: ^0.2.1
  timeline_tile: ^2.0.0
  dotted_border: ^2.1.0



  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  url_launcher: ^6.2.6
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - lib/assets/images/flutte_logo.png
    - lib/assets/images/dart_logo.png
    - lib/assets/images/d_logo.png
    - lib/assets/json/users.json
    - lib/assets/json/recruiters.json
