// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3LiglFL2mswC2qhFjNTAFluoOS0d1Nks',
    appId: '1:487481489545:web:fe2545316842ad7019ae58',
    messagingSenderId: '487481489545',
    projectId: 'adopte-1-candidat',
    authDomain: 'adopte-1-candidat.firebaseapp.com',
    storageBucket: 'adopte-1-candidat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEW_NWgWfdZ74QOwwEiQRsumlj9UFTMLw',
    appId: '1:487481489545:android:2d5905cb5172472c19ae58',
    messagingSenderId: '487481489545',
    projectId: 'adopte-1-candidat',
    storageBucket: 'adopte-1-candidat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhZFimRfPYdf94yuT-3huDNIj3iBpcWCY',
    appId: '1:487481489545:ios:c4fdd6f0d270f18f19ae58',
    messagingSenderId: '487481489545',
    projectId: 'adopte-1-candidat',
    storageBucket: 'adopte-1-candidat.appspot.com',
    iosBundleId: 'com.example.jobMatchingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhZFimRfPYdf94yuT-3huDNIj3iBpcWCY',
    appId: '1:487481489545:ios:c4fdd6f0d270f18f19ae58',
    messagingSenderId: '487481489545',
    projectId: 'adopte-1-candidat',
    storageBucket: 'adopte-1-candidat.appspot.com',
    iosBundleId: 'com.example.jobMatchingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3LiglFL2mswC2qhFjNTAFluoOS0d1Nks',
    appId: '1:487481489545:web:c698638832e3af2019ae58',
    messagingSenderId: '487481489545',
    projectId: 'adopte-1-candidat',
    authDomain: 'adopte-1-candidat.firebaseapp.com',
    storageBucket: 'adopte-1-candidat.appspot.com',
  );

}